### PR TITLE
 refactoring for results retrieving

### PR DESCRIPTION
**Pull request by RadoslawKubas**
Not fully tested, but tested with Loggly Http and Generic Syslog and works fine.

### CODE REVIEW

**Comment by RadoslawKubas** [comment]
I committed some changes/fixes to this PR. First of all I tried to make my code more IoC friendly so needs to redesign architecture. Basically I created new interface (ILogger) with LogAsync method and bool result, and implemented it in all loggers. Now with new NetworkResilienceLogger class future logs resending may be implemented.

**Comment by dansiegel** [comment]
I want to try to keep it simple... and cross platform... currently this particular plugin could be used by WPF, UWP, and XF Prism Applications. Let's back out a few of your changes. I like where you were going by returning a Task<boo>. That could then be used to determine whether or not to persist the log...

**Comment by RadoslawKubas** [comment]
Sure, right, good idea to keep it simple and maximum cross platform and actually I did some changes in this direction. As maybe you noticed I redesigned again little bit structure. 

Grylog, Loggly and Syslog can be used as before in any project, only new thing is ILogger implementation (I rollback some my previous changes in class structure). 

If persistent logs are necessary there is new NetworkResilienceLogger (ILoggerFacade). It is possible to inject ILogger and IUnsentLogsRepository, so it is cross platform too. I added an example of use in LoggingDemo. The only platform dependent thing left, is implementation of IUnsentLogsRepository, but I think on some level it have to be platform dependent. 

I created new library (XamarinLogsRepository) and put there  IUnsentLogsRepository implementation for XF. Actually didn't test it yet :) but will test tomorrow. Actually, some part of this implementation code can be moved to cross platform library, but I used Application.Current.Properties, so this part will works only in XF.

**Comment by dansiegel** [comment]
PR's need to be smaller and focus on a single thing. What you had originally looked pretty good, but this has started to balloon.

**Comment by RadoslawKubas** [comment]
Yes, yes, as I mentioned before I created this PR for easier show some idea and discuss direction, not for making those sometimes to large changes all together :) Anyway, I will create another PR, just with this small fix for problem with UrlEncoder and later step by step another changes if only agreed.

Hmm.. just first I need to find, some good idea how to create this small PR without rolling back this fork to ground.

**Comment by RadoslawKubas** [comment]
OK, done, just small fix and later after this will be accepted, I will create next one with LogAsync and interface for it to return value from loggers, if I understand you liked that direction more or less :)

**Comment by RadoslawKubas** [comment]
I closed this as it is just prototype of ILoggerAsync route.

**Pull request closed without merging**
